import numpy as np
from scipy.optimize import curve_fit

from .gibson_lanni import SPSFGibsonLanni


def fit_sigma(x: np.ndarray, y: np.ndarray) -> float:
    """
    Fit a 1D Gaussian to the input profile and return estimated sigma.

    Parameters
    ----------
    x : np.ndarray
        Coordinate values (e.g., distance).
    y : np.ndarray
        Intensity profile (must be unimodal and positive).

    Returns
    -------
    float
        Estimated standard deviation (sigma) of the fitted Gaussian.

    Raises
    ------
    RuntimeError
        If curve fitting fails.
    """

    def _gaussian(x, a, mu, sigma):
        return (a / (sigma * np.sqrt(2 * np.pi))) * np.exp(
            -0.5 * ((x - mu) / sigma) ** 2
        )

    a0 = np.max(y)
    mu0 = x[np.argmax(y)]
    sigma0 = np.std(x) / 4  # loose guess

    try:
        params, _ = curve_fit(_gaussian, x, y, p0=[a0, mu0, sigma0])
    except Exception as e:
        raise RuntimeError("Gaussian fit failed.") from e

    return params[2]


def estimate_psf_sigmas(
    wavelength: float,
    na: float,
    magnification: int,
    ns: float = 1.33,
    ng: float = 1.5,
    ni: float = 1.333,
    tg: float = 170,
    confocal: bool = True,
) -> tuple[float, float]:
    """
    Estimate lateral and axial standard deviations (sigmas) of a 3D PSF generated by the Gibson-Lanni model.

    This function generates a 3D point spread function (PSF) volume using the Gibson-Lanni model
    with specified optical parameters and isotropic voxel spacing, then fits Gaussian profiles to the
    lateral (XY) and axial (Z) intensity distributions to estimate their characteristic sigmas
    in physical units (microns).

    Parameters
    ----------
    spacing : tuple of float
        Original voxel spacing (not used for PSF generation).
    wavelength : float
        Illumination wavelength in microns.
    na : float
        Numerical aperture of the objective.
    magnification : int
        Microscope magnification.
    ns : float, optional
        Specimen refractive index (RI). Default is 1.33.
    ng : float, optional
        Coverslip RI. Default is 1.5.
    ni : float, optional
        Refractive index of immersion liquid. Default is 1.333.
    tg : float, optional
        Coverslip thickness in microns. Default is 170.
    confocal : bool, optional
        Whether to simulate a confocal PSF. Default is True.

    Returns
    -------
    sigma_lat : float
        Lateral standard deviation of the PSF in microns (X and Y).
    sigma_ax : float
        Axial standard deviation of the PSF in microns (Z).
    """
    # Use isotropic voxel spacing = wavelength / 50 (microns)
    voxel_spacing = wavelength / 100  # float

    # Calculate shape size (number of voxels) per dimension for 2 um cube
    shape_size = int(2 // voxel_spacing)

    # Voxel spacing for axial and lateral dimensions (both same here)
    res_ax = voxel_spacing
    res_lat = voxel_spacing

    psf_generator = SPSFGibsonLanni(
        shape=(shape_size, shape_size, shape_size),
        NA=na,
        wavelength=wavelength,
        M=magnification,
        ns=ns,
        ng0=ng,
        ng=ng,
        ni0=ni,
        ni=ni,
        tg0=tg,
        tg=tg,
        res_lateral=res_lat,
        res_axial=res_ax,
        use_square=confocal,
    )
    psf = psf_generator()

    center = shape_size // 2
    lat_profile = psf[center, center, :]
    ax_profile = psf[:, center, center]

    lat_coords = np.arange(shape_size) * res_lat
    ax_coords = np.arange(shape_size) * res_ax

    sigma_lat = fit_sigma(lat_coords, lat_profile)
    sigma_ax = fit_sigma(ax_coords, ax_profile)

    return sigma_lat, sigma_ax
